<?php

/***************************************************************
 * Extension Manager/Repository config file for ext "openweather".
 *
 * Auto generated by Extension Builder 2020-08-01
 *
 * Manual updates:
 * Only the data in the array - everything else is removed by next
 * writing. "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Open Weather',
    'description' => 'Scheduler task to import and diaplay Current and Forecast OpenWeather data in Frontend.',
    'category' => 'services',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'nirmalya.mondal@gmail.com',
    'author_company' => 'https://ashokatree.net/',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '/fileadmin/openweather/',
    'clearCacheOnLoad' => 1,
    'version' => '10.0.0',
    'constraints' => [
        'depends' =>[
            'typo3' => '10.0.0 - 10.99.99',
            'scheduler' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'suggests' => [],
];
